# Generated by Django 5.1.4 on 2024-12-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_comment_comment_type_alter_event_speakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('general', 'نظر عادی'), ('approved', 'نظر تایید شده'), ('expert', 'نظر متخصص'), ('ai', 'نظر هوش مصنوعی')], default='general', max_length=20),
        ),
    ]
