# Generated by Django 5.1.4 on 2024-12-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_comment_comment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type_of_event',
            field=models.CharField(blank=True, choices=[('kargah', 'کارگاه'), ('seminar', 'سمینار'), ('conferance', 'کنفرانس'), ('dore', 'دوره'), ('webinar', 'وبینار'), ('bootcamp', 'بوتکمپ')], max_length=100, null=True),
        ),
    ]
