# Generated by Django 5.1.4 on 2024-12-14 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_major'),
        ('home', '0005_event_type_of_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_major', to='event.major'),
        ),
    ]
