# Generated by Django 5.1.4 on 2024-12-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_event_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_of_event',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
